export const DISCTRICT_DESCRIPTION = "DISTRICT";
export const CITY_DESCRIPTION = "CITY";
export const PRODUCT_TYPE_DESCRIPTION = "PROUCT_TYPE";
export const SHOP_DESCRIPTION = "SHOP";
export const SHOP_CONTACT_DESCRIPTION = "SHOP_CONTACT";
export const SHOP_SPOT_DESCRIPTION = "SHOP_SPOT";
export const AREA_CONTACT_DESCRIPTION = "AREA_CONTACT";
export const AREA_SPOT_DESCRIPTION = "AREA_SPOT";

export const PRODUCT_TYPE_ADD_REQUEST = "PRODUCT_TYPE_ADD_REQUEST";
export const PRODUCT_TYPE_ADD_SUCCESS = "PRODUCT_TYPE_ADD_SUCCESS";
export const PRODUCT_TYPE_ADD_FAIL = "PRODUCT_TYPE_ADD_FAIL";
export const PRODUCT_TYPE_ADD_DELETE = "PRODUCT_TYPE_ADD_DELETE";

export const DISTRICT_ADD_REQUEST = "DISTRICT_ADD_REQUEST";
export const DISTRICT_ADD_SUCCESS = "DISTRICT_ADD_SUCCESS";
export const DISTRICT_ADD_FAIL = "DISTRICT_ADD_FAIL";
export const DISTRICT_ADD_DELETE = "DISTRICT_ADD_DELETE";

export const CITI_ADD_REQUEST = "CITI_ADD_REQUEST";
export const CITI_ADD_SUCCESS = "CITI_ADD_SUCCESS";
export const CITI_ADD_FAIL = "CITI_ADD_FAIL";
export const CITI_ADD_DELETE = "CITI_ADD_DELETE";

export const GET_CITES_LIST_REQUEST = "GET_CITES_LIST_REQUEST";
export const GET_CITES_LIST_SUCCESS = "GET_CITES_LIST_SUCCESS";
export const GET_CITES_LIST_FAIL = "GET_CITES_LIST_FAIL";
export const GET_CITES_LIST_DELETE = "GET_CITES_LIST_DELETE";

export const GET_ALL_CITIES_REQUEST = "GET_ALL_CITIES_REQUEST";
export const GET_ALL_CITIES_SUCCESS = "GET_ALL_CITIES_SUCCESS";
export const GET_ALL_CITIES_FAIL = "GET_ALL_CITIES_FAIL";
export const GET_ALL_CITIES_DELETE = "GET_ALL_CITIES_DELETE";

export const DISTRICT_REQUEST = "DISTRICT_REQUEST";
export const DISTRICT_SUCCESS = "DISTRICT_SUCCESS";
export const DISTRICT_FAIL = "DISTRICT_FAIL";
export const DISTRICT_DELETE = "DISTRICT_DELETE";

export const DISTRICT_ADD_DESC_REQUEST = "DISTRICT_ADD_DESC_REQUEST";
export const DISTRICT_ADD_DESC_SUCCESS = "DISTRICT_ADD_DESC_SUCCESS";
export const DISTRICT_ADD_DESC_FAIL = "DISTRICT_ADD_DESC_FAIL";
export const DISTRICT_ADD_DESC_DELETE = "DISTRICT_ADD_DESC_DELETE";

export const ADD_DESC_REQUEST = "ADD_DESC_REQUEST";
export const ADD_DESC_SUCCESS = "ADD_DESC_SUCCESS";
export const ADD_DESC_FAIL = "ADD_DESC_FAIL";
export const ADD_DESC_DELETE = "ADD_DESC_DELETE";

export const ADD_SHOP_REQUEST = "ADD_SHOP_REQUEST";
export const ADD_SHOP_SUCCESS = "ADD_SHOP_SUCCESS";
export const ADD_SHOP_DELETE_SUCCESS = "ADD_SHOP_DELETE_SUCCESS";
export const ADD_SHOP_FAIL = "ADD_SHOP_FAIL";
export const ADD_SHOP_DELETE = "ADD_SHOP_DELETE";

export const ADD_CONTACT_REQUEST = "ADD_CONTACT_REQUEST";
export const ADD_CONTACT_SUCCESS = "ADD_CONTACT_SUCCESS";
export const ADD_CONTACT_FAIL = "ADD_CONTACT_FAIL";
export const ADD_CONTACT_DELETE = "ADD_CONTACT_DELETE";

export const GET_FULL_DESCRIPTION_REQUEST = "GET_FULL_DESCRIPTION_REQUEST";
export const GET_FULL_DESCRIPTION_SUCCESS = "GET_FULL_DESCRIPTION_SUCCESS";
export const GET_FULL_DESCRIPTION_FAIL = "GET_FULL_DESCRIPTION_FAIL";
export const GET_FULL_DESCRIPTION_DELETE = "GET_FULL_DESCRIPTION_DELETE";

export const ACTIVE_DESCRIPTION_REQUEST = "ACTIVE_DESCRIPTION_REQUEST";
export const ACTIVE_DESCRIPTION_SUCCESS = "ACTIVE_DESCRIPTION_SUCCESS";
export const ACTIVE_DESCRIPTION_FAIL = "ACTIVE_DESCRIPTION_FAIL";
export const ACTIVE_DESCRIPTION_DELETE = "ACTIVE_DESCRIPTION_DELETE";

export const GET_SHOPS_LIST_REQUEST = "GET_SHOPS_LIST_REQUEST";
export const GET_SHOPS_LIST_SUCCESS = "GET_SHOPS_LIST_SUCCESS";
export const GET_SHOPS_LIST_FAIL = "GET_SHOPS_LIST_FAIL";
export const GET_SHOPS_LIST_DELETE = "GET_SHOPS_LIST_DELETE";

export const GET_CONTACT_LIST_REQUEST = "GET_CONTACT_LIST_REQUEST";
export const GET_CONTACT_LIST_SUCCESS = "GET_CONTACT_LIST_SUCCESS";
export const GET_CONTACT_LIST_FAIL = "GET_CONTACT_LIST_FAIL";
export const GET_CONTACT_LIST_DELETE = "GET_CONTACT_LIST_DELETE";

export const GET_SHOP_REQUEST = "GET_SHOP_REQUEST";
export const GET_SHOP_SUCCESS = "GET_SHOP_SUCCESS";
export const GET_SHOP_FAIL = "GET_SHOP_FAIL";
export const GET_SHOP_DELETE = "GET_SHOP_DELETE";

export const EDIT_SHOP_REQUEST = "EDIT_SHOP_REQUEST";
export const EDIT_SHOP_SUCCESS = "EDIT_SHOP_SUCCESS";
export const EDIT_SHOP_FAIL = "EDIT_SHOP_FAIL";
export const EDIT_SHOP_DELETE = "EDIT_SHOP_DELETE";

//Flags -- global
export const SET_FLAG_DESC_TRUE = "SET_FLAG_DESC_TRUE";
export const SET_FLAG_DESC_FALSE = "SET_FLAG_DESC_FALSE";
export const SET_FLAG_ADD_DESC_FALSE = "SET_FLAG_ADD_DESC_FALSE";
export const SET_FLAG_ADD_DESC_TRUE = "SET_FLAG_ADD_DESC_TRUE";

export const SET_FLAG_INFO_FALSE = "SET_FLAG_INFO_FALSE";
export const SET_FLAG_INFO_TRUE = "SET_FLAG_INFO_TRUE";
export const SET_FLAG_CITY_TRUE = "SET_FLAG_CITY_TRUE";
export const SET_FLAG_CITY_FALSE = "SET_FLAG_CITY_FALSE";
export const SET_FLAG_SHOP_TRUE = "SET_FLAG_SHOP_TRUE";
export const SET_FLAG_SHOP_FALSE = "SET_FLAG_SHOP_FALSE";
export const SET_FLAG_IMAGE_TRUE = "SET_FLAG_IMAGE_TRUE";
export const SET_FLAG_IMAGE_FALSE = "SET_FLAG_IMAGE_FALSE";

export const SET_WINDOW_FLAG_FALSE = "SET_WINDOW_FLAG_FALSE";
export const SET_WINDOW_FLAG_TRUE = "SET_WINDOW_FLAG_TRUE";
export const SET_WINDOW_FLAG_DELETE = "SET_WINDOW_FLAG_DELETE";

export const SAVE_IMAGE_REDUX = "SAVE_IMAGE_REDUX";
export const DELETE_IMAGE_REDUX = "DELETE_IMAGE_REDUX";

export const ADD_IMAGE_REQUEST = "ADD_IMAGE_REQUEST";
export const ADD_IMAGE_SUCCESS = "ADD_IMAGE_SUCCESS";
export const ADD_IMAGE_FAIL = "ADD_IMAGE_FAIL";
export const ADD_IMAGE_DELETE = "ADD_IMAGE_DELETE";

export const ADD_SHOP_SPOT_REQUEST = "ADD_SHOP_SPOT_REQUEST";
export const ADD_SHOP_SPOT_SUCCESS = "ADD_SHOP_SPOT_SUCCESS";
export const ADD_SHOP_SPOT_FAIL = "ADD_SHOP_SPOT_FAIL";
export const ADD_SHOP_SPOT_DELETE = "ADD_SHOP_SPOT_DELETE";

export const GET_SOPTS_LIST_REQUEST = "GET_SOPTS_LIST_REQUEST";
export const GET_SOPTS_LIST_SUCCESS = "GET_SOPTS_LIST_SUCCESS";
export const GET_SOPTS_LIST_FAIL = "GET_SOPTS_LIST_FAIL";
export const GET_SOPTS_LIST_DELETE = "GET_SOPTS_LIST_DELETE";

export const GET_SPOT_REQUEST = "GET_SPOT_REQUEST";
export const GET_SPOT_SUCCESS = "GET_SPOT_SUCCESS";
export const GET_SPOT_FAIL = "GET_SPOT_FAIL";
export const GET_SPOT_DELETE = "GET_SPOT_DELETE";

export const EDIT_SHOP_SPOT_REQUEST = "EDIT_SHOP_SPOT_REQUEST";
export const EDIT_SHOP_SPOT_SUCCESS = "EDIT_SHOP_SPOT_SUCCESS";
export const EDIT_SHOP_SPOT_FAIL = "EDIT_SHOP_SPOT_FAIL";
export const EDIT_SHOP_SPOT_DELETE = "EDIT_SHOP_SPOT_DELETE";

export const SET_CITY_FLAG_DESC_TRUE = "SET_CITY_FLAG_DESC_TRUE";
export const SET_CITY_FLAG_DESC_FALSE = "SET_CITY_FLAG_DESC_FALSE";

export const SET_FLAG_ADD_TRUE = "SET_FLAG_ADD_TRUE";
export const SET_FLAG_ADD_FALSE = "SET_FLAG_ADD_FALSE";

//NavbarTopAdmin

export const HAMBURGER = "hamburger";
export const LOGOUT = "Logout";

// CitiesList

export const EMPTY_LIST = "empty list";

//
export const DISTRICT = "district";
export const CITY = "city";
export const UNACTIVE = "unactive";
export const ACTIVE = "active";
export const ZERO = "0";
export const ONE = "1";
export const TWO = "2";
export const THREE = "3";
