export const DISTRICT_ADD_REQUEST = "DISTRICT_ADD_REQUEST";
export const DISTRICT_ADD_SUCCESS = "DISTRICT_ADD_SUCCESS";
export const DISTRICT_ADD_FAIL = "DISTRICT_ADD_FAIL";
export const DISTRICT_ADD_DELETE = "DISTRICT_ADD_DELETE";

export const DISTRICT_REQUEST = "DISTRICT_REQUEST";
export const DISTRICT_SUCCESS = "DISTRICT_SUCCESS";
export const DISTRICT_FAIL = "DISTRICT_FAIL";
export const DISTRICT_DELETE = "DISTRICT_DELETE";

export const DISTRICT_ADD_DESC_REQUEST = "DISTRICT_ADD_DESC_REQUEST";
export const DISTRICT_ADD_DESC_SUCCESS = "DISTRICT_ADD_DESC_SUCCESS";
export const DISTRICT_ADD_DESC_FAIL = "DISTRICT_ADD_DESC_FAIL";
export const DISTRICT_ADD_DESC_DELETE = "DISTRICT_ADD_DESC_DELETE";
