export const DISCTRICT_DESCRIPTION = "DISTRICT";
export const CITY_DESCRIPTION = "CITY";
export const PRODUCT_TYPE_DESCRIPTION = "PROUCT_TYPE";
export const SHOP_DESCRIPTION = "SHOP";

export const PRODUCT_TYPE_ADD_REQUEST = "PRODUCT_TYPE_ADD_REQUEST";
export const PRODUCT_TYPE_ADD_SUCCESS = "PRODUCT_TYPE_ADD_SUCCESS";
export const PRODUCT_TYPE_ADD_FAIL = "PRODUCT_TYPE_ADD_FAIL";
export const PRODUCT_TYPE_ADD_DELETE = "PRODUCT_TYPE_ADD_DELETE";

export const DISTRICT_ADD_REQUEST = "DISTRICT_ADD_REQUEST";
export const DISTRICT_ADD_SUCCESS = "DISTRICT_ADD_SUCCESS";
export const DISTRICT_ADD_FAIL = "DISTRICT_ADD_FAIL";
export const DISTRICT_ADD_DELETE = "DISTRICT_ADD_DELETE";

export const CITI_ADD_REQUEST = "CITI_ADD_REQUEST";
export const CITI_ADD_SUCCESS = "CITI_ADD_SUCCESS";
export const CITI_ADD_FAIL = "CITI_ADD_FAIL";
export const CITI_ADD_DELETE = "CITI_ADD_DELETE";

export const GET_CITES_LIST_REQUEST = "GET_CITES_LIST_REQUEST";
export const GET_CITES_LIST_SUCCESS = "GET_CITES_LIST_SUCCESS";
export const GET_CITES_LIST_FAIL = "GET_CITES_LIST_FAIL";
export const GET_CITES_LIST_DELETE = "GET_CITES_LIST_DELETE";

export const DISTRICT_REQUEST = "DISTRICT_REQUEST";
export const DISTRICT_SUCCESS = "DISTRICT_SUCCESS";
export const DISTRICT_FAIL = "DISTRICT_FAIL";
export const DISTRICT_DELETE = "DISTRICT_DELETE";

export const DISTRICT_ADD_DESC_REQUEST = "DISTRICT_ADD_DESC_REQUEST";
export const DISTRICT_ADD_DESC_SUCCESS = "DISTRICT_ADD_DESC_SUCCESS";
export const DISTRICT_ADD_DESC_FAIL = "DISTRICT_ADD_DESC_FAIL";
export const DISTRICT_ADD_DESC_DELETE = "DISTRICT_ADD_DESC_DELETE";

export const ADD_DESC_REQUEST = "ADD_DESC_REQUEST";
export const ADD_DESC_SUCCESS = "ADD_DESC_SUCCESS";
export const ADD_DESC_FAIL = "ADD_DESC_FAIL";
export const ADD_DESC_DELETE = "ADD_DESC_DELETE";

export const ADD_SHOP_REQUEST = "ADD_SHOP_REQUEST";
export const ADD_SHOP_SUCCESS = "ADD_SHOP_SUCCESS";
export const ADD_SHOP_FAIL = "ADD_SHOP_FAIL";
export const ADD_SHOP_DELETE = "ADD_SHOP_DELETE";

export const GET_FULL_DESCRIPTION_REQUEST = "GET_FULL_DESCRIPTION_REQUEST";
export const GET_FULL_DESCRIPTION_SUCCESS = "GET_FULL_DESCRIPTION_SUCCESS";
export const GET_FULL_DESCRIPTION_FAIL = "GET_FULL_DESCRIPTION_FAIL";
export const GET_FULL_DESCRIPTION_DELETE = "GET_FULL_DESCRIPTION_DELETE";

export const ACTIVE_DESCRIPTION_REQUEST = "ACTIVE_DESCRIPTION_REQUEST";
export const ACTIVE_DESCRIPTION_SUCCESS = "ACTIVE_DESCRIPTION_SUCCESS";
export const ACTIVE_DESCRIPTION_FAIL = "ACTIVE_DESCRIPTION_FAIL";
export const ACTIVE_DESCRIPTION_DELETE = "ACTIVE_DESCRIPTION_DELETE";

export const GET_SHOPS_LIST_REQUEST = "GET_SHOPS_LIST_REQUEST";
export const GET_SHOPS_LIST_SUCCESS = "GET_SHOPS_LIST_SUCCESS";
export const GET_SHOPS_LIST_FAIL = "GET_SHOPS_LIST_FAIL";
export const GET_SHOPS_LIST_DELETE = "GET_SHOPS_LIST_DELETE";

//Flags -- global
export const SET_FLAG_DESC_TRUE = "SET_FLAG_DESC_TRUE";
export const SET_FLAG_DESC_FALSE = "SET_FLAG_DESC_FALSE";
export const SET_FLAG_ADD_DESC_FALSE = "SET_FLAG_ADD_DESC_FALSE";
export const SET_FLAG_ADD_DESC_TRUE = "SET_FLAG_ADD_DESC_TRUE";

export const SET_FLAG_INFO_FALSE = "SET_FLAG_INFO_FALSE";
export const SET_FLAG_INFO_TRUE = "SET_FLAG_INFO_TRUE";
export const SET_FLAG_CITY_TRUE = "SET_FLAG_CITY_TRUE";
export const SET_FLAG_CITY_FALSE = "SET_FLAG_CITY_FALSE";

export const SET_WINDOW_FLAG_FALSE = "SET_WINDOW_FLAG_FALSE";
export const SET_WINDOW_FLAG_TRUE = "SET_WINDOW_FLAG_TRUE";
export const SET_WINDOW_FLAG_DELETE = "SET_WINDOW_FLAG_DELETE";
