export const ADD_AREA_REQUEST = "ADD_AREA_REQUEST";
export const ADD_AREA_SUCCESS = "ADD_AREA_SUCCESS";
export const ADD_AREA_FAIL = "ADD_AREA_FAIL";
export const ADD_AREA_DELETE = "ADD_AREA_DELETE";

export const GET_AREA_LIST_REQUEST = "GET_AREA_LIST_REQUEST";
export const GET_AREA_LIST_SUCCESS = "GET_AREA_LIST_SUCCESS";
export const GET_AREA_LIST_FAIL = "GET_AREA_LIST_FAIL";
export const GET_AREA_LIST_DELETE = "GET_AREA_LIST_DELETE";

export const GET_AREA_REQUEST = "GET_AREA_REQUEST";
export const GET_AREA_SUCCESS = "GET_AREA_SUCCESS";
export const GET_AREA_FAIL = "GET_AREA_FAIL";
export const GET_AREA_DELETE = "GET_AREA_DELETE";

export const EDIT_AREA_REQUEST = "EDIT_AREA_REQUEST";
export const EDIT_AREA_SUCCESS = "EDIT_AREA_SUCCESS";
export const EDIT_AREA_FAIL = "EDIT_AREA_FAIL";
export const EDIT_AREA_DELETE = "EDIT_AREA_DELETE";

export const GET_AREA_CONTACT_LIST_REQUEST = "GET_AREA_CONTACT_LIST_REQUEST";
export const GET_AREA_CONTACT_LIST_SUCCESS = "GET_AREA_CONTACT_LIST_SUCCESS";
export const GET_AREA_CONTACT_LIST_FAIL = "GET_AREA_CONTACT_LIST_FAIL";
export const GET_AREA_CONTACT_LIST_DELETE = "GET_AREA_CONTACT_LIST_DELETE";

export const TIME_AUT = 4000;
