export const SORT_BY_LNG_REQUEST = "SORT_BY_LNG_REQUEST";
export const SORT_BY_LNG_SUCCESS = "SORT_BY_LNG_SUCCESS";
export const SORT_BY_LNG_FAIL = "SORT_BY_LNG_FAIL";
export const SORT_BY_LNG_DELETE = "SORT_BY_LNG_DELETE";

export const ADD_PRODUCT_CAT_REQUEST = "ADD_PRODUCT_CAT_REQUEST";
export const ADD_PRODUCT_CAT_SUCCESS = "ADD_PRODUCT_CAT_SUCCESS";
export const ADD_PRODUCT_CAT_FAIL = "ADD_PRODUCT_CAT_FAIL";
export const ADD_PRODUCT_CAT_DELETE = "ADD_PRODUCT_CAT_DELETE";

export const GET_PRODUCT_CAT_LIST_REQUEST = "GET_PRODUCT_CAT_LIST_REQUEST";
export const GET_PRODUCT_CAT_LIST_SUCCESS = "GET_PRODUCT_CAT_LIST_SUCCESS";
export const GET_PRODUCT_CAT_LIST_FAIL = "GET_PRODUCT_CAT_LIST_FAIL";
export const GET_PRODUCT_CAT_LIST_DELETE = "GET_PRODUCT_CAT_LIST_DELETE";
export const ADD_PRODUCT_CAT_DELETE_SUCCESS = "ADD_PRODUCT_CAT_DELETE_SUCCESS";

export const GET_PRODUCT_SUBCAT_LIST_REQUEST =
  "GET_PRODUCT_SUBCAT_LIST_REQUEST";
export const GET_PRODUCT_SUBCAT_LIST_SUCCESS =
  "GET_PRODUCT_SUBCAT_LIST_SUCCESS";
export const GET_PRODUCT_SUBCAT_LIST_FAIL = "GET_PRODUCT_SUBCAT_LIST_FAIL";
export const GET_PRODUCT_SUBCAT_LIST_DELETE = "GET_PRODUCT_SUBCAT_LIST_DELETE";

export const ADD_PRODUCT_SUBCAT_REQUEST = "ADD_PRODUCT_SUBCAT_REQUEST";
export const ADD_PRODUCT_SUBCAT_SUCCESS = "ADD_PRODUCT_SUBCAT_SUCCESS";
export const ADD_PRODUCT_SUBCAT_FAIL = "ADD_PRODUCT_SUBCAT_FAIL";
export const ADD_PRODUCT_SUBCAT_DELETE = "ADD_PRODUCT_SUBCAT_DELETE";

export const GET_PRODUCT_SUBCAT_REQUEST = "GET_PRODUCT_SUBCAT_REQUEST";
export const GET_PRODUCT_SUBCAT_SUCCESS = "GET_PRODUCT_SUBCAT_SUCCESS";
export const GET_PRODUCT_SUBCAT_FAIL = "GET_PRODUCT_SUBCAT_FAIL";
export const GET_PRODUCT_SUBCAT_DELETE = "GET_PRODUCT_SUBCAT_DELETE";

export const EDIT_PRODUCT_SUBCAT_REQUEST = "EDIT_PRODUCT_SUBCAT_REQUEST";
export const EDIT_PRODUCT_SUBCAT_SUCCESS = "EDIT_PRODUCT_SUBCAT_SUCCESS";
export const EDIT_PRODUCT_SUBCAT_FAIL = "EDIT_PRODUCT_SUBCAT_FAIL";
export const EDIT_PRODUCT_SUBCAT_DELETE = "EDIT_PRODUCT_SUBCAT_DELETE";

export const GET_PRODUCT_LIST_REQUEST = "GET_PRODUCT_LIST_REQUEST";
export const GET_PRODUCT_LIST_SUCCESS = "GET_PRODUCT_LIST_SUCCESS";
export const GET_PRODUCT_LIST_FAIL = "GET_PRODUCT_LIST_FAIL";
export const GET_PRODUCT_LIST_DELETE = "GET_PRODUCT_LIST_DELETE";

export const GET_PRODUCT_CAT_REQUEST = "GET_PRODUCT_CAT_REQUEST";
export const GET_PRODUCT_CAT_SUCCESS = "GET_PRODUCT_CAT_SUCCESS";
export const GET_PRODUCT_CAT_FAIL = "GET_PRODUCT_CAT_FAIL";
export const GET_PRODUCT_CAT_DELETE = "GET_PRODUCT_CAT_DELETE";

export const SEARCH_SELECTED_LNG = "SEARCH_SELECTED_LNG";
export const SEARCH_SELECTED_DELETE = "SEARCH_SELECTED_DELETE";
export const SEARCH_SELECTED_CATEGORY = "SEARCH_SELECTED_CATEGORY";
export const SEARCH_SELECTED_SUBCATEGORY = "SEARCH_SELECTED_SUBCATEGORY"
