export const ADD_PRODUCT_CAT_REQUEST = "ADD_PRODUCT_CAT_REQUEST";
export const ADD_PRODUCT_CAT_SUCCESS = "ADD_PRODUCT_CAT_SUCCESS";
export const ADD_PRODUCT_CAT_FAIL = "ADD_PRODUCT_CAT_FAIL";
export const ADD_PRODUCT_CAT_DELETE = "ADD_PRODUCT_CAT_DELETE";

export const GET_PRODUCT_CAT_LIST_REQUEST = "GET_PRODUCT_CAT_LIST_REQUEST";
export const GET_PRODUCT_CAT_LIST_SUCCESS = "GET_PRODUCT_CAT_LIST_SUCCESS";
export const GET_PRODUCT_CAT_LIST_FAIL = "GET_PRODUCT_CAT_LIST_FAIL";
export const GET_PRODUCT_CAT_LIST_DELETE = "GET_PRODUCT_CAT_LIST_DELETE";
export const ADD_PRODUCT_CAT_DELETE_SUCCESS = "ADD_PRODUCT_CAT_DELETE_SUCCESS";
