export const SORT_BY_LNG_REQUEST = "SORT_BY_LNG_REQUEST";
export const SORT_BY_LNG_SUCCESS = "SORT_BY_LNG_SUCCESS";
export const SORT_BY_LNG_FAIL = "SORT_BY_LNG_FAIL";
export const SORT_BY_LNG_DELETE = "SORT_BY_LNG_DELETE";

export const ADD_PRODUCT_CAT_REQUEST = "ADD_PRODUCT_CAT_REQUEST";
export const ADD_PRODUCT_CAT_SUCCESS = "ADD_PRODUCT_CAT_SUCCESS";
export const ADD_PRODUCT_CAT_FAIL = "ADD_PRODUCT_CAT_FAIL";
export const ADD_PRODUCT_CAT_DELETE = "ADD_PRODUCT_CAT_DELETE";

export const GET_PRODUCT_CAT_LIST_REQUEST = "GET_PRODUCT_CAT_LIST_REQUEST";
export const GET_PRODUCT_CAT_LIST_SUCCESS = "GET_PRODUCT_CAT_LIST_SUCCESS";
export const GET_PRODUCT_CAT_LIST_FAIL = "GET_PRODUCT_CAT_LIST_FAIL";
export const GET_PRODUCT_CAT_LIST_DELETE = "GET_PRODUCT_CAT_LIST_DELETE";
export const ADD_PRODUCT_CAT_DELETE_SUCCESS = "ADD_PRODUCT_CAT_DELETE_SUCCESS";

export const GET_PRODUCT_SUBCAT_LIST_REQUEST =
  "GET_PRODUCT_SUBCAT_LIST_REQUEST";
export const GET_PRODUCT_SUBCAT_LIST_SUCCESS =
  "GET_PRODUCT_SUBCAT_LIST_SUCCESS";
export const GET_PRODUCT_SUBCAT_LIST_FAIL = "GET_PRODUCT_SUBCAT_LIST_FAIL";
export const GET_PRODUCT_SUBCAT_LIST_DELETE = "GET_PRODUCT_SUBCAT_LIST_DELETE";

export const ADD_PRODUCT_SUBCAT_REQUEST = "ADD_PRODUCT_SUBCAT_REQUEST";
export const ADD_PRODUCT_SUBCAT_SUCCESS = "ADD_PRODUCT_SUBCAT_SUCCESS";
export const ADD_PRODUCT_SUBCAT_FAIL = "ADD_PRODUCT_SUBCAT_FAIL";
export const ADD_PRODUCT_SUBCAT_DELETE = "ADD_PRODUCT_SUBCAT_DELETE";

export const GET_PRODUCT_SUBCAT_REQUEST = "GET_PRODUCT_SUBCAT_REQUEST";
export const GET_PRODUCT_SUBCAT_SUCCESS = "GET_PRODUCT_SUBCAT_SUCCESS";
export const GET_PRODUCT_SUBCAT_FAIL = "GET_PRODUCT_SUBCAT_FAIL";
export const GET_PRODUCT_SUBCAT_DELETE = "GET_PRODUCT_SUBCAT_DELETE";

export const EDIT_PRODUCT_SUBCAT_REQUEST = "EDIT_PRODUCT_SUBCAT_REQUEST";
export const EDIT_PRODUCT_SUBCAT_SUCCESS = "EDIT_PRODUCT_SUBCAT_SUCCESS";
export const EDIT_PRODUCT_SUBCAT_FAIL = "EDIT_PRODUCT_SUBCAT_FAIL";
export const EDIT_PRODUCT_SUBCAT_DELETE = "EDIT_PRODUCT_SUBCAT_DELETE";

export const GET_PRODUCT_LIST_REQUEST = "GET_PRODUCT_LIST_REQUEST";
export const GET_PRODUCT_LIST_SUCCESS = "GET_PRODUCT_LIST_SUCCESS";
export const GET_PRODUCT_LIST_FAIL = "GET_PRODUCT_LIST_FAIL";
export const GET_PRODUCT_LIST_DELETE = "GET_PRODUCT_LIST_DELETE";

export const GET_PRODUCT_CAT_REQUEST = "GET_PRODUCT_CAT_REQUEST";
export const GET_PRODUCT_CAT_SUCCESS = "GET_PRODUCT_CAT_SUCCESS";
export const GET_PRODUCT_CAT_FAIL = "GET_PRODUCT_CAT_FAIL";
export const GET_PRODUCT_CAT_DELETE = "GET_PRODUCT_CAT_DELETE";

export const SEARCH_SELECTED_LNG = "SEARCH_SELECTED_LNG";
export const SEARCH_SELECTED_DELETE = "SEARCH_SELECTED_DELETE";
export const SEARCH_SELECTED_CATEGORY = "SEARCH_SELECTED_CATEGORY";
export const SEARCH_SELECTED_SUBCATEGORY = "SEARCH_SELECTED_SUBCATEGORY"
export const SEARCH_SELECTED_DELETE_NO_LNG = "SEARCH_SELECTED_DELETE_NO_LNG"

export const GET_MYPRODUCT_LIST_REQUEST = "GET_MYPRODUCT_LIST_REQUEST"
export const GET_MYPRODUCT_LIST_SUCCESS = "GET_MYPRODUCT_LIST_SUCCESS"
export const GET_MYPRODUCT_LIST_FAIL = "GET_MYPRODUCT_LIST_FAIL"
export const GET_MYPRODUCT_LIST_DELETE = "GET_MYPRODUCT_LIST_DELETE"

export const ADD_MYPRODUCT_REQUEST = "ADD_MYPRODUCT_REQUEST"
export const ADD_MYPRODUCT_SUCCESS = "ADD_MYPRODUCT_SUCCESS"
export const ADD_MYPRODUCT_FAIL = "ADD_MYPRODUCT_FAIL"
export const ADD_MYPRODUCT_DELETE = "ADD_MYPRODUCT_DELETE"

export const ADD_MY_IMAGE_REQUEST = "ADD_MY_IMAGE_REQUEST"
export const ADD_IMAGE_MY_SUCCESS = "ADD_IMAGE_MY_SUCCESS"
export const ADD_IMAGE_MY_FAIL = "ADD_IMAGE_MY_FAIL"
export const ADD_IMAGE_MY_DELETE = "ADD_IMAGE_MY_DELETE"

export const UPDATE_MY_IMAGE_REQUEST = "UPDATE_MY_IMAGE_REQUEST"
export const UPDATE_IMAGE_MY_SUCCESS = "UPDATE_IMAGE_MY_SUCCESS"
export const UPDATE_IMAGE_MY_FAIL = "UPDATE_IMAGE_MY_FAIL"
export const UPDATE_IMAGE_MY_DELETE = "UPDATE_IMAGE_MY_DELETE"

export const GET_MY_IMAGE_REQUEST = "GET_MY_IMAGE_REQUEST"
export const GET_MY_IMAGE_SUCCESS = "GET_MY_IMAGE_SUCCESS"
export const GET_MY_IMAGE_FAIL = "GET_MY_IMAGE_FAIL"
export const GET_MY_IMAGE_DELETE = "GET_MY_IMAGE_DELETE"

export const DELETE_MY_IMAGE_REQUEST = "DELETE_MY_IMAGE_REQUEST"
export const DELETE_MY_IMAGE_SUCCESS = "DELETE_MY_IMAGE_SUCCESS"
export const DELETE_MY_IMAGE_FAIL = "DELETE_MY_IMAGE_FAIL"
export const DELETE_MY_IMAGE_DELETE = "DELETE_MY_IMAGE_DELETE"

export const DELETE_MY_PRODUCT_REQUEST = "DELETE_MY_PRODUCT_REQUEST"
export const DELETE_MY_PRODUCT_SUCCESS = "DELETE_MY_PRODUCT_SUCCESS"
export const DELETE_MY_PRODUCT_FAIL = "DELETE_MY_PRODUCT_FAIL"
export const DELETE_MY_PRODUCT_DELETE = "DELETE_MY_PRODUCT_DELETE"

export const ADD_OFFER_REQUEST = "ADD_OFFER_REQUEST"
export const ADD_OFFER_SUCCESS = "ADD_OFFER_SUCCESS"
export const ADD_OFFER_FAIL = "ADD_OFFER_FAIL"
export const ADD_OFFER_DELETE = "ADD_OFFER_DELETE"

export const ADD_LOG_REQUEST = "ADD_LOG_REQUEST"
export const ADD_LOG_SUCCESS = "ADD_LOG_SUCCESS"
export const ADD_LOG_FAIL = "ADD_LOG_FAIL"

export const GET_MYOFFERS_LIST_REQUEST = "GET_MYOFFERS_LIST_REQUEST"
export const GET_MYOFFERS_LIST_SUCCESS = "GET_MYOFFERS_LIST_SUCCESS"
export const GET_MYOFFERS_LIST_FAIL = "GET_MYOFFERS_LIST_FAIL"
export const GET_MYOFFERS_LIST_DELETE = "GET_MYOFFERS_LIST_DELETE"

export const DELETE_MYOFFERS_REQUEST = "DELETE_MYOFFERS_REQUEST"
export const DELETE_MYOFFERS_SUCCESS = "DELETE_MYOFFERS_SUCCESS"
export const DELETE_MYOFFERS_FAIL = "DELETE_MYOFFERS_FAIL"
export const DELETE_MYOFFERS_DELETE = "DELETE_MYOFFERS_DELETE"

export const ADD_QUANTITY_OFFER_REQUEST = "ADD_QUANTITY_OFFER_REQUEST"
export const ADD_QUANTITY_OFFER_SUCCESS = "ADD_QUANTITY_OFFER_SUCCESS"
export const ADD_QUANTITY_OFFER_FAIL = "ADD_QUANTITY_OFFER_FAIL"
export const ADD_QUANTITY_OFFER_DELETE = "ADD_QUANTITY_OFFER_DELETE"

export const GET_MYOFFER_REQUEST = "GET_MYOFFER_REQUEST"
export const GET_MYOFFER_SUCCESS = "GET_MYOFFER_SUCCESS"
export const GET_MYOFFER_FAIL = "GET_MYOFFER_FAIL"
export const GET_MYOFFER_DELETE = "GET_MYOFFER_DELETE"

export const UPDATE_SPOT_PICK_UP_REQUEST = "UPDATE_SPOT_PICK_UP_REQUEST"
export const UPDATE_SPOT_PICK_UP_SUCCESS = "UPDATE_SPOT_PICK_UP_SUCCESS"
export const UPDATE_SPOT_PICK_UP_FAIL = "UPDATE_SPOT_PICK_UP_FAIL"
export const UPDATE_SPOT_PICK_UP_DELETE = "UPDATE_SPOT_PICK_UP_DELETE"
