# Generated by Django 4.0.4 on 2022-08-08 15:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Descriptions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(blank=True, max_length=255, null=True)),
                ('language', models.CharField(blank=True, max_length=2, null=True)),
                ('obj_type', models.CharField(blank=True, max_length=50, null=True)),
                ('obj_id', models.CharField(blank=True, max_length=10, null=True)),
                ('date_of_entry', models.DateTimeField(auto_now=True, null=True)),
                ('date_of_change', models.DateTimeField(blank=True, null=True)),
                ('creator', models.CharField(blank=True, max_length=5, null=True)),
                ('modifier', models.CharField(blank=True, max_length=5, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Districts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=50, null=True, unique=True)),
                ('date_of_entry', models.DateTimeField(auto_now=True, null=True)),
                ('date_of_change', models.DateTimeField(blank=True, null=True)),
                ('is_active', models.BooleanField(blank=True, null=True)),
                ('creator', models.CharField(blank=True, max_length=50, null=True)),
                ('modifier', models.CharField(blank=True, max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ProductType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=50, null=True, unique=True)),
                ('date_of_entry', models.DateTimeField(auto_now=True, null=True)),
                ('date_of_change', models.DateTimeField(blank=True, null=True)),
                ('is_active', models.BooleanField(blank=True, null=True)),
                ('creator', models.CharField(blank=True, max_length=50, null=True)),
                ('modifier', models.CharField(blank=True, max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Shops',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('nip', models.CharField(max_length=20, unique=True)),
                ('city', models.CharField(max_length=40)),
                ('street', models.CharField(max_length=50)),
                ('no_building', models.CharField(max_length=10)),
                ('post_code', models.CharField(max_length=10)),
                ('post', models.CharField(max_length=40)),
                ('latitude', models.CharField(max_length=20)),
                ('longitude', models.CharField(max_length=20)),
                ('date_of_entry', models.DateTimeField(auto_now=True, null=True)),
                ('date_of_change', models.DateTimeField(blank=True, null=True)),
                ('modifier', models.CharField(blank=True, max_length=50, null=True)),
                ('creator', models.CharField(blank=True, max_length=50, null=True)),
                ('is_active', models.BooleanField(blank=True, null=True)),
                ('photo', models.CharField(blank=True, max_length=150, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ShopsARC',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_shops', models.IntegerField()),
                ('name', models.CharField(max_length=50, unique=True)),
                ('nip', models.CharField(max_length=20)),
                ('city', models.CharField(max_length=40)),
                ('street', models.CharField(max_length=50)),
                ('no_building', models.CharField(max_length=10)),
                ('post_code', models.CharField(max_length=10)),
                ('post', models.CharField(max_length=40)),
                ('latitude', models.CharField(max_length=20)),
                ('longitude', models.CharField(max_length=20)),
                ('date_of_entry', models.DateTimeField(auto_now=True, null=True)),
                ('date_of_change', models.DateTimeField(blank=True, null=True)),
                ('modifier', models.CharField(blank=True, max_length=50, null=True)),
                ('creator', models.CharField(blank=True, max_length=50, null=True)),
                ('is_active', models.BooleanField(blank=True, null=True)),
                ('photo', models.CharField(max_length=150)),
                ('type_of_change', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='ShopsDescription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=255)),
                ('language', models.CharField(max_length=5)),
                ('date_of_entry', models.DateTimeField(auto_now=True, null=True)),
                ('creator', models.CharField(blank=True, max_length=50, null=True)),
                ('is_active', models.BooleanField(blank=True, null=True)),
                ('date_of_change', models.DateTimeField(blank=True, null=True)),
                ('modifier', models.CharField(blank=True, max_length=50, null=True)),
                ('type_of_change', models.CharField(max_length=50)),
                ('id_shops', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='base.shops')),
            ],
        ),
        migrations.CreateModel(
            name='ShopsContact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('surname', models.CharField(max_length=50, unique=True)),
                ('email', models.CharField(max_length=150, unique=True)),
                ('phone', models.CharField(max_length=20)),
                ('date_of_entry', models.DateTimeField(auto_now=True, null=True)),
                ('creator', models.CharField(blank=True, max_length=50, null=True)),
                ('is_active', models.BooleanField(blank=True, null=True)),
                ('date_of_change', models.DateTimeField(blank=True, null=True)),
                ('modifier', models.CharField(blank=True, max_length=50, null=True)),
                ('type_of_change', models.CharField(max_length=50)),
                ('id_shops', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='base.shops')),
            ],
        ),
        migrations.CreateModel(
            name='Place_of_pickups',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=50, null=True)),
                ('citi', models.CharField(blank=True, max_length=50, null=True)),
                ('poste_code', models.CharField(blank=True, max_length=10, null=True)),
                ('street', models.CharField(blank=True, max_length=50, null=True)),
                ('number', models.CharField(blank=True, max_length=15, null=True)),
                ('lat', models.CharField(blank=True, max_length=30, null=True)),
                ('lng', models.CharField(blank=True, max_length=30, null=True)),
                ('date_of_entry', models.DateTimeField(auto_now=True, null=True)),
                ('date_of_change', models.DateTimeField(blank=True, null=True)),
                ('is_active', models.BooleanField(blank=True, null=True)),
                ('creator', models.CharField(blank=True, max_length=50, null=True)),
                ('modifier', models.CharField(blank=True, max_length=50, null=True)),
                ('id_district', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='base.districts')),
            ],
        ),
        migrations.CreateModel(
            name='Citis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=50, null=True)),
                ('post_code', models.CharField(blank=True, max_length=10, null=True)),
                ('date_of_entry', models.DateTimeField(auto_now=True, null=True)),
                ('date_of_change', models.DateTimeField(blank=True, null=True)),
                ('is_active', models.BooleanField(blank=True, null=True)),
                ('creator', models.CharField(blank=True, max_length=50, null=True)),
                ('modifier', models.CharField(blank=True, max_length=50, null=True)),
                ('id_district', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='base.districts')),
            ],
        ),
    ]
