# Generated by Django 4.0.4 on 2022-08-08 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shopscontact',
            name='email',
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name='shopscontact',
            name='name',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='shopscontact',
            name='surname',
            field=models.CharField(max_length=50),
        ),
    ]
