# Generated by Django 4.0.5 on 2023-03-17 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='shopsspot',
            name='kind',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='shopsspotarc',
            name='kind',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
