# Generated by Django 4.0.4 on 2022-08-09 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_alter_shopscontact_email_alter_shopscontact_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shops',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='shopsarc',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
