# Generated by Django 4.0.5 on 2022-06-24 08:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_place_of_pickups_remove_districts_description_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Citi_description',
            new_name='Citis_description',
        ),
    ]
