# Generated by Django 4.0.5 on 2023-03-20 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_shopsspot_kind_shopsspotarc_kind'),
    ]

    operations = [
        migrations.AlterField(
            model_name='areacontactarc',
            name='description',
            field=models.CharField(max_length=512),
        ),
        migrations.AlterField(
            model_name='areasdescriptions',
            name='description',
            field=models.CharField(blank=True, max_length=512, null=True),
        ),
        migrations.AlterField(
            model_name='areasspotdescriptions',
            name='description',
            field=models.CharField(blank=True, max_length=512, null=True),
        ),
        migrations.AlterField(
            model_name='areasspotdescriptionsarc',
            name='description',
            field=models.CharField(blank=True, max_length=512, null=True),
        ),
        migrations.AlterField(
            model_name='citiesdescriptions',
            name='description',
            field=models.CharField(blank=True, max_length=512, null=True),
        ),
        migrations.AlterField(
            model_name='descriptions',
            name='description',
            field=models.CharField(blank=True, max_length=512, null=True),
        ),
        migrations.AlterField(
            model_name='myproductsdescriptions',
            name='description',
            field=models.CharField(blank=True, max_length=512, null=True),
        ),
        migrations.AlterField(
            model_name='myproductsdescriptionsarc',
            name='description',
            field=models.CharField(blank=True, max_length=512, null=True),
        ),
        migrations.AlterField(
            model_name='productdescriptions',
            name='description',
            field=models.CharField(blank=True, max_length=512, null=True),
        ),
        migrations.AlterField(
            model_name='productsubtypesdescriptions',
            name='description',
            field=models.CharField(blank=True, max_length=512, null=True),
        ),
        migrations.AlterField(
            model_name='producttypesdescriptions',
            name='description',
            field=models.CharField(blank=True, max_length=512, null=True),
        ),
        migrations.AlterField(
            model_name='shopscontact',
            name='description',
            field=models.CharField(max_length=512),
        ),
        migrations.AlterField(
            model_name='shopscontactarc',
            name='description',
            field=models.CharField(max_length=512),
        ),
        migrations.AlterField(
            model_name='shopsdescriptions',
            name='description',
            field=models.CharField(blank=True, max_length=512, null=True),
        ),
        migrations.AlterField(
            model_name='shopsspotdescriptions',
            name='description',
            field=models.CharField(blank=True, max_length=512, null=True),
        ),
    ]
