# Generated by Django 4.0.4 on 2022-08-24 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_alter_shops_photo_alter_shopsarc_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='shops',
            name='bank_account',
            field=models.CharField(blank=True, max_length=34, null=True),
        ),
        migrations.AddField(
            model_name='shopsarc',
            name='bank_account',
            field=models.CharField(blank=True, max_length=34, null=True),
        ),
    ]
