# Generated by Django 4.0.5 on 2022-07-04 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_citis_creator_citis_modifier_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Descriptions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(blank=True, max_length=255, null=True)),
                ('language', models.CharField(blank=True, max_length=2, null=True)),
                ('type', models.CharField(blank=True, max_length=50, null=True)),
                ('date_of_entry', models.DateTimeField(auto_now=True, null=True)),
                ('date_of_change', models.DateTimeField(blank=True, null=True)),
                ('is_active', models.BooleanField()),
                ('creator', models.CharField(blank=True, max_length=5, null=True)),
                ('modifier', models.CharField(blank=True, max_length=5, null=True)),
            ],
        ),
    ]
