# Generated by Django 4.0.4 on 2022-08-25 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_shops_bank_account_shopsarc_bank_account'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shopsarc',
            name='name',
            field=models.CharField(max_length=50),
        ),
    ]
