# Generated by Django 4.0.5 on 2023-05-29 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_alter_areasdescriptions_description_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='myproductsphotos',
            name='modifier',
        ),
        migrations.AddField(
            model_name='myproductsphotos',
            name='uniqe_id',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
