# Generated by Django 4.0.5 on 2022-07-04 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0005_descriptions'),
    ]

    operations = [
        migrations.RenameField(
            model_name='descriptions',
            old_name='type',
            new_name='obj_type',
        ),
        migrations.AddField(
            model_name='descriptions',
            name='obj_id',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
