# Generated by Django 4.0.4 on 2022-08-27 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0005_alter_shopsarc_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shopsarc',
            name='no_building',
            field=models.CharField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='shopsarc',
            name='post_code',
            field=models.CharField(max_length=1000),
        ),
    ]
