# Generated by Django 4.0.5 on 2022-07-04 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0006_rename_type_descriptions_obj_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='descriptions',
            name='is_active',
            field=models.BooleanField(auto_created=True),
        ),
    ]
