# Generated by Django 4.0.5 on 2022-07-04 09:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0007_alter_descriptions_is_active'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='descriptions',
            name='is_active',
        ),
    ]
