# Generated by Django 4.0.5 on 2023-05-31 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0007_myproductsphotos_unique_date'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MyProductsARC',
        ),
        migrations.DeleteModel(
            name='MyProductsPhotosARC',
        ),
        migrations.AddField(
            model_name='myproducts',
            name='is_delete',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AddField(
            model_name='myproductsphotos',
            name='is_delete',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AddField(
            model_name='myproductsphotos',
            name='modifier',
            field=models.CharField(blank=True, max_length=5, null=True),
        ),
    ]
