# Generated by Django 4.0.4 on 2022-08-27 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0007_alter_shopsarc_no_building_alter_shopsarc_post_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shops',
            name='no_building',
            field=models.CharField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='shops',
            name='post_code',
            field=models.CharField(max_length=1000),
        ),
    ]
