# Generated by Django 4.0.5 on 2023-06-27 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0008_delete_myproductsarc_delete_myproductsphotosarc_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producttypes',
            name='name',
            field=models.CharField(max_length=50),
        ),
    ]
