# Generated by Django 4.0.4 on 2022-08-27 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0008_alter_shops_no_building_alter_shops_post_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shops',
            name='bank_account',
            field=models.CharField(blank=True, max_length=3400, null=True),
        ),
        migrations.AlterField(
            model_name='shops',
            name='city',
            field=models.CharField(max_length=4000),
        ),
        migrations.AlterField(
            model_name='shops',
            name='creator',
            field=models.CharField(blank=True, max_length=5000, null=True),
        ),
        migrations.AlterField(
            model_name='shops',
            name='latitude',
            field=models.CharField(max_length=2000),
        ),
        migrations.AlterField(
            model_name='shops',
            name='longitude',
            field=models.CharField(max_length=2000),
        ),
        migrations.AlterField(
            model_name='shops',
            name='modifier',
            field=models.CharField(blank=True, max_length=5000, null=True),
        ),
        migrations.AlterField(
            model_name='shops',
            name='name',
            field=models.CharField(max_length=5000, unique=True),
        ),
        migrations.AlterField(
            model_name='shops',
            name='nip',
            field=models.CharField(max_length=2000, unique=True),
        ),
        migrations.AlterField(
            model_name='shops',
            name='post',
            field=models.CharField(max_length=4000),
        ),
        migrations.AlterField(
            model_name='shops',
            name='street',
            field=models.CharField(max_length=5000),
        ),
    ]
