# Generated by Django 4.0.5 on 2022-07-07 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0008_remove_descriptions_is_active'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='districts_description',
            name='id_district',
        ),
        migrations.RemoveField(
            model_name='place_of_pickups_description',
            name='id_place_of_pickup',
        ),
        migrations.AlterField(
            model_name='districts',
            name='name',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True),
        ),
        migrations.DeleteModel(
            name='Citis_description',
        ),
        migrations.DeleteModel(
            name='Districts_description',
        ),
        migrations.DeleteModel(
            name='Place_of_pickups_description',
        ),
    ]
