# Generated by Django 4.0.5 on 2023-06-28 11:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0009_alter_producttypes_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='MyProductsOffered',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.FloatField()),
                ('current_quantity', models.FloatField()),
                ('barrel_bulk', models.CharField(max_length=5)),
                ('offer_from', models.DateTimeField()),
                ('offer_to', models.DateTimeField()),
                ('country_of_origin', models.CharField(blank=True, max_length=50, null=True)),
                ('term_of_validity', models.DateTimeField()),
                ('date_of_entry', models.DateTimeField(auto_now=True)),
                ('date_of_change', models.DateTimeField(blank=True, null=True)),
                ('creator', models.CharField(max_length=5)),
                ('modifier', models.CharField(blank=True, max_length=5, null=True)),
                ('is_active', models.BooleanField()),
                ('id_my_product', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='base.myproducts')),
            ],
        ),
        migrations.CreateModel(
            name='MyProductsPrice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.FloatField()),
                ('sale_price', models.FloatField(blank=True, null=True)),
                ('price_30_day', models.FloatField(blank=True, null=True)),
                ('currency', models.CharField(blank=True, max_length=5, null=True)),
                ('package_size', models.FloatField()),
                ('id_my_product_offered', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='base.myproductsoffered')),
            ],
        ),
        migrations.CreateModel(
            name='MyProductsOfferedDoc',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.FloatField()),
                ('date_of_entry', models.DateTimeField(auto_now=True)),
                ('creator', models.CharField(max_length=5)),
                ('type_document', models.CharField(blank=True, max_length=50, null=True)),
                ('is_add', models.BooleanField()),
                ('id_my_product_offered', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='base.myproductsoffered')),
            ],
        ),
    ]
