# Generated by Django 4.0.4 on 2022-08-27 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0009_alter_shops_bank_account_alter_shops_city_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shopsarc',
            name='bank_account',
            field=models.CharField(blank=True, max_length=3400, null=True),
        ),
        migrations.AlterField(
            model_name='shopsarc',
            name='city',
            field=models.CharField(max_length=4000),
        ),
        migrations.AlterField(
            model_name='shopsarc',
            name='creator',
            field=models.CharField(blank=True, max_length=5000, null=True),
        ),
        migrations.AlterField(
            model_name='shopsarc',
            name='latitude',
            field=models.CharField(max_length=2000),
        ),
        migrations.AlterField(
            model_name='shopsarc',
            name='longitude',
            field=models.CharField(max_length=2000),
        ),
        migrations.AlterField(
            model_name='shopsarc',
            name='modifier',
            field=models.CharField(blank=True, max_length=5000, null=True),
        ),
        migrations.AlterField(
            model_name='shopsarc',
            name='name',
            field=models.CharField(max_length=5000),
        ),
        migrations.AlterField(
            model_name='shopsarc',
            name='nip',
            field=models.CharField(max_length=2000),
        ),
        migrations.AlterField(
            model_name='shopsarc',
            name='no_building',
            field=models.CharField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='shopsarc',
            name='post',
            field=models.CharField(max_length=4000),
        ),
        migrations.AlterField(
            model_name='shopsarc',
            name='post_code',
            field=models.CharField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='shopsarc',
            name='street',
            field=models.CharField(max_length=5000),
        ),
        migrations.AlterField(
            model_name='shopsarc',
            name='type_of_change',
            field=models.CharField(max_length=5000),
        ),
    ]
