# Generated by Django 4.0.5 on 2022-07-12 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0009_remove_districts_description_id_district_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='citis',
            name='post_code',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
