# Generated by Django 4.0.5 on 2022-09-23 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0011_shopscontact_description_alter_shopscontact_creator_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shops',
            name='bank_account',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
        migrations.AlterField(
            model_name='shops',
            name='city',
            field=models.CharField(max_length=40),
        ),
        migrations.AlterField(
            model_name='shops',
            name='creator',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='shops',
            name='latitude',
            field=models.CharField(max_length=25),
        ),
        migrations.AlterField(
            model_name='shops',
            name='longitude',
            field=models.CharField(max_length=25),
        ),
        migrations.AlterField(
            model_name='shops',
            name='modifier',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='shops',
            name='name',
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='shops',
            name='nip',
            field=models.CharField(max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name='shops',
            name='no_building',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='shops',
            name='post',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='shops',
            name='post_code',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='shops',
            name='street',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='shopsarc',
            name='type_of_change',
            field=models.CharField(max_length=50),
        ),
    ]
