# Generated by Django 4.0.5 on 2023-07-07 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0011_myproductsoffered_barrel_bulk_long_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myproductsoffered',
            name='country_of_origin',
            field=models.CharField(blank=True, max_length=5, null=True),
        ),
    ]
