# Generated by Django 4.0.5 on 2023-07-08 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0012_alter_myproductsoffered_country_of_origin'),
    ]

    operations = [
        migrations.AddField(
            model_name='myproductsoffered',
            name='unique_key',
            field=models.FloatField(blank=True, max_length=15, null=True),
        ),
    ]
