# Generated by Django 4.0.4 on 2022-07-20 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0012_shops_shopsarc_shopsdescription_shopscontact'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shops',
            name='nip',
            field=models.CharField(max_length=20, unique=True),
        ),
    ]
