# Generated by Django 4.0.5 on 2022-09-23 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0012_alter_shops_bank_account_alter_shops_city_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ShopsContactARC',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_shops', models.IntegerField()),
                ('name', models.CharField(max_length=30)),
                ('surname', models.CharField(max_length=40)),
                ('email', models.CharField(max_length=100)),
                ('phone', models.CharField(max_length=20)),
                ('description', models.CharField(max_length=255)),
                ('date_of_entry', models.DateTimeField(auto_now=True, null=True)),
                ('creator', models.CharField(blank=True, max_length=20, null=True)),
                ('is_active', models.BooleanField(blank=True, null=True)),
                ('date_of_change', models.DateTimeField(blank=True, null=True)),
                ('modifier', models.CharField(blank=True, max_length=20, null=True)),
                ('type_of_change', models.CharField(max_length=50)),
            ],
        ),
        migrations.AddField(
            model_name='shops',
            name='delivery',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='shops',
            name='range',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='shopsarc',
            name='delivery',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='shopsarc',
            name='range',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='shopsarc',
            name='bank_account',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
        migrations.AlterField(
            model_name='shopsarc',
            name='city',
            field=models.CharField(max_length=40),
        ),
        migrations.AlterField(
            model_name='shopsarc',
            name='creator',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='shopsarc',
            name='latitude',
            field=models.CharField(max_length=25),
        ),
        migrations.AlterField(
            model_name='shopsarc',
            name='longitude',
            field=models.CharField(max_length=25),
        ),
        migrations.AlterField(
            model_name='shopsarc',
            name='modifier',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='shopsarc',
            name='name',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='shopsarc',
            name='nip',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='shopsarc',
            name='no_building',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='shopsarc',
            name='post',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='shopsarc',
            name='post_code',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='shopsarc',
            name='street',
            field=models.CharField(max_length=50),
        ),
    ]
