# Generated by Django 4.0.5 on 2022-09-23 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0013_shopscontactarc_shops_delivery_shops_range_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='shopscontactarc',
            name='date_of_archiv',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
