# Generated by Django 4.0.5 on 2023-07-11 07:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0013_myproductsoffered_unique_key'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='myproductsoffereddoc',
            name='is_add',
        ),
    ]
