# Generated by Django 4.0.4 on 2022-07-22 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0014_alter_shops_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='shops',
            name='date_of_change',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='shops',
            name='modifier',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
