# Generated by Django 4.0.5 on 2023-07-26 05:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0014_remove_myproductsoffereddoc_is_add'),
    ]

    operations = [
        migrations.CreateModel(
            name='ErrorLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_error', models.DateTimeField(auto_now=True)),
                ('user', models.CharField(blank=True, max_length=20, null=True)),
                ('function_name', models.CharField(blank=True, max_length=30, null=True)),
                ('error_class', models.CharField(blank=True, max_length=30, null=True)),
                ('error_name', models.CharField(blank=True, max_length=512, null=True)),
                ('pgcode', models.CharField(blank=True, max_length=10, null=True)),
                ('pgerror', models.CharField(blank=True, max_length=512, null=True)),
            ],
        ),
    ]
