# Generated by Django 4.0.5 on 2022-09-26 10:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0014_shopscontactarc_date_of_archiv'),
    ]

    operations = [
        migrations.CreateModel(
            name='ShopsSpotARC',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_shops', models.IntegerField()),
                ('id_spot', models.IntegerField()),
                ('name', models.CharField(max_length=50, unique=True)),
                ('city', models.CharField(max_length=40)),
                ('street', models.CharField(max_length=50)),
                ('no_building', models.CharField(max_length=30)),
                ('post_code', models.CharField(max_length=20)),
                ('post', models.CharField(max_length=30)),
                ('latitude', models.CharField(max_length=25)),
                ('longitude', models.CharField(max_length=25)),
                ('date_of_entry', models.DateTimeField(auto_now=True, null=True)),
                ('date_of_change', models.DateTimeField(blank=True, null=True)),
                ('modifier', models.CharField(blank=True, max_length=20, null=True)),
                ('creator', models.CharField(blank=True, max_length=20, null=True)),
                ('is_active', models.BooleanField(blank=True, null=True)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='')),
                ('delivery', models.BooleanField(blank=True, null=True)),
                ('range', models.IntegerField(default=0)),
                ('type_of_change', models.CharField(max_length=50)),
                ('date_of_archiv', models.DateTimeField(auto_now=True, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='shops',
            name='delivery',
        ),
        migrations.RemoveField(
            model_name='shops',
            name='range',
        ),
        migrations.RemoveField(
            model_name='shopsarc',
            name='delivery',
        ),
        migrations.RemoveField(
            model_name='shopsarc',
            name='range',
        ),
        migrations.AddField(
            model_name='shopsarc',
            name='date_of_archiv',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AddField(
            model_name='shopscontactarc',
            name='id_contact',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='ShopsSpot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('city', models.CharField(max_length=40)),
                ('street', models.CharField(max_length=50)),
                ('no_building', models.CharField(max_length=30)),
                ('post_code', models.CharField(max_length=20)),
                ('post', models.CharField(max_length=30)),
                ('latitude', models.CharField(max_length=25)),
                ('longitude', models.CharField(max_length=25)),
                ('date_of_entry', models.DateTimeField(auto_now=True, null=True)),
                ('date_of_change', models.DateTimeField(blank=True, null=True)),
                ('modifier', models.CharField(blank=True, max_length=20, null=True)),
                ('creator', models.CharField(blank=True, max_length=20, null=True)),
                ('is_active', models.BooleanField(blank=True, null=True)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='')),
                ('delivery', models.BooleanField(blank=True, null=True)),
                ('range', models.IntegerField(default=0)),
                ('id_shops', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='base.shops')),
            ],
        ),
    ]
