# Generated by Django 4.0.5 on 2022-09-29 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0015_shopsspotarc_remove_shops_delivery_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shopsspot',
            name='name',
            field=models.CharField(max_length=50),
        ),
    ]
