# Generated by Django 4.0.5 on 2023-07-26 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0015_errorlog'),
    ]

    operations = [
        migrations.AddField(
            model_name='errorlog',
            name='code_position',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='errorlog',
            name='text_position',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
    ]
