# Generated by Django 4.0.4 on 2022-07-23 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0015_shops_date_of_change_shops_modifier'),
    ]

    operations = [
        migrations.AddField(
            model_name='shopscontact',
            name='surname',
            field=models.CharField(default=1, max_length=50, unique=True),
            preserve_default=False,
        ),
    ]
