# Generated by Django 4.0.5 on 2022-10-05 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0016_alter_shopsspot_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shopsspotarc',
            name='name',
            field=models.CharField(max_length=50),
        ),
    ]
