# Generated by Django 4.0.4 on 2022-07-26 16:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0016_shopscontact_surname'),
    ]

    operations = [
        migrations.AddField(
            model_name='shopsarc',
            name='id_shops',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='base.shops'),
        ),
    ]
