# Generated by Django 4.0.5 on 2023-08-03 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0016_errorlog_code_position_errorlog_text_position'),
    ]

    operations = [
        migrations.CreateModel(
            name='AxiosErrorLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_error', models.DateTimeField(blank=True, null=True)),
                ('data_error_saveed', models.DateTimeField(auto_now=True)),
                ('user', models.CharField(blank=True, max_length=20, null=True)),
                ('function_name', models.CharField(blank=True, max_length=30, null=True)),
                ('error_code', models.CharField(blank=True, max_length=30, null=True)),
                ('error_detail', models.CharField(blank=True, max_length=50, null=True)),
                ('status', models.CharField(blank=True, max_length=20, null=True)),
                ('method', models.CharField(blank=True, max_length=50, null=True)),
                ('url', models.CharField(blank=True, max_length=256, null=True)),
            ],
        ),
        migrations.AlterField(
            model_name='myproductsoffered',
            name='unique_key',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
