# Generated by Django 4.0.4 on 2022-07-26 17:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0017_shopsarc_id_shops'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shopsarc',
            name='id',
        ),
        migrations.AlterField(
            model_name='shopsarc',
            name='id_shops',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='base.shops'),
            preserve_default=False,
        ),
    ]
