# Generated by Django 4.0.5 on 2022-10-05 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0017_alter_shopsspotarc_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shopsarc',
            name='date_of_entry',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='shopscontactarc',
            name='date_of_entry',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='shopsspotarc',
            name='date_of_entry',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
