# Generated by Django 4.0.4 on 2022-07-26 17:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0018_remove_shopsarc_id_alter_shopsarc_id_shops'),
    ]

    operations = [
        migrations.AddField(
            model_name='shopsarc',
            name='id',
            field=models.BigAutoField(auto_created=True, default=1, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='shopsarc',
            name='id_shops',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='base.shops'),
        ),
    ]
