# Generated by Django 4.0.5 on 2023-08-07 05:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0018_rename_data_error_saveed_axioserrorlog_data_error_saved_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='axioserrorlog',
            name='param',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='axioserrorlog',
            name='text',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
    ]
