# Generated by Django 4.0.5 on 2022-10-05 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0018_alter_shopsarc_date_of_entry_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='shopsspot',
            name='type_of_change',
            field=models.CharField(default='test', max_length=50),
            preserve_default=False,
        ),
    ]
