# Generated by Django 4.0.5 on 2023-08-21 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0019_axioserrorlog_param_axioserrorlog_text'),
    ]

    operations = [
        migrations.CreateModel(
            name='AxiosErrorLogRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_error_saved', models.DateTimeField(auto_now=True)),
                ('user_saved', models.CharField(blank=True, max_length=20, null=True)),
                ('request_text', models.CharField(blank=True, max_length=2050, null=True)),
            ],
        ),
    ]
