# Generated by Django 4.0.5 on 2022-10-25 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0019_shopsspot_type_of_change'),
    ]

    operations = [
        migrations.AddField(
            model_name='shopsarc',
            name='archiver',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='shopscontactarc',
            name='archiver',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='shopsspotarc',
            name='archiver',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
