# Generated by Django 4.0.4 on 2022-07-26 17:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0019_shopsarc_id_alter_shopsarc_id_shops'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shopsarc',
            name='id_shops',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='base.shops'),
        ),
    ]
