# Generated by Django 4.1.2 on 2022-12-01 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0020_shopsarc_archiver_shopscontactarc_archiver_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='districts',
            name='latitude',
            field=models.CharField(blank=True, max_length=25, null=True),
        ),
        migrations.AddField(
            model_name='districts',
            name='longitude',
            field=models.CharField(blank=True, max_length=25, null=True),
        ),
    ]
