# Generated by Django 4.0.5 on 2023-09-07 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0020_axioserrorlogrequest'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shopsspotarc',
            name='city',
            field=models.CharField(max_length=50),
        ),
    ]
