# Generated by Django 4.0.5 on 2022-12-07 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0021_districts_latitude_districts_longitude'),
    ]

    operations = [
        migrations.AddField(
            model_name='citis',
            name='latitude',
            field=models.CharField(blank=True, max_length=25, null=True),
        ),
        migrations.AddField(
            model_name='citis',
            name='longitude',
            field=models.CharField(blank=True, max_length=25, null=True),
        ),
    ]
