# Generated by Django 4.0.4 on 2022-07-26 17:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0021_remove_shopsarc_id_alter_shopsarc_id_shops'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ShopsARC',
        ),
    ]
