# Generated by Django 4.0.5 on 2022-12-13 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0022_citis_latitude_citis_longitude'),
    ]

    operations = [
        migrations.CreateModel(
            name='Areas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('nip', models.CharField(max_length=20, unique=True)),
                ('city', models.CharField(max_length=40)),
                ('street', models.CharField(max_length=50)),
                ('no_building', models.CharField(max_length=30)),
                ('post_code', models.CharField(max_length=20)),
                ('post', models.CharField(max_length=30)),
                ('latitude', models.CharField(max_length=25)),
                ('longitude', models.CharField(max_length=25)),
                ('date_of_entry', models.DateTimeField(auto_now=True, null=True)),
                ('date_of_change', models.DateTimeField(blank=True, null=True)),
                ('modifier', models.CharField(blank=True, max_length=20, null=True)),
                ('creator', models.CharField(blank=True, max_length=20, null=True)),
                ('is_active', models.BooleanField(blank=True, null=True)),
                ('bank_account', models.CharField(blank=True, max_length=40, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='AreasARC',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_shops', models.IntegerField()),
                ('name', models.CharField(max_length=50)),
                ('nip', models.CharField(max_length=20)),
                ('city', models.CharField(max_length=40)),
                ('street', models.CharField(max_length=50)),
                ('no_building', models.CharField(max_length=30)),
                ('post_code', models.CharField(max_length=20)),
                ('post', models.CharField(max_length=30)),
                ('latitude', models.CharField(max_length=25)),
                ('longitude', models.CharField(max_length=25)),
                ('date_of_entry', models.DateTimeField(blank=True, null=True)),
                ('date_of_change', models.DateTimeField(blank=True, null=True)),
                ('modifier', models.CharField(blank=True, max_length=20, null=True)),
                ('creator', models.CharField(blank=True, max_length=20, null=True)),
                ('is_active', models.BooleanField(blank=True, null=True)),
                ('bank_account', models.CharField(blank=True, max_length=40, null=True)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='')),
                ('type_of_change', models.CharField(max_length=50)),
                ('date_of_archiv', models.DateTimeField(auto_now=True, null=True)),
                ('archiver', models.CharField(blank=True, max_length=20, null=True)),
            ],
        ),
    ]
