# Generated by Django 4.0.5 on 2022-12-19 09:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0024_alter_areas_name_alter_areas_nip_alter_shops_name_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='areasarc',
            old_name='id_shops',
            new_name='id_areas',
        ),
    ]
