# Generated by Django 4.0.5 on 2022-12-19 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0025_rename_id_shops_areasarc_id_areas'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='areasarc',
            name='photo',
        ),
        migrations.AddField(
            model_name='areas',
            name='type_of_change',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
