# Generated by Django 4.0.5 on 2022-12-19 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0026_remove_areasarc_photo_areas_type_of_change'),
    ]

    operations = [
        migrations.AlterField(
            model_name='areasarc',
            name='type_of_change',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
