# Generated by Django 4.0.5 on 2022-12-21 12:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0027_alter_areasarc_type_of_change'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shopsspot',
            name='city',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='base.citis'),
        ),
    ]
