# Generated by Django 4.1.2 on 2023-01-09 16:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0028_alter_shopsspot_city'),
    ]

    operations = [
        migrations.CreateModel(
            name='AreaContactARC',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_shops', models.IntegerField()),
                ('name', models.CharField(max_length=30)),
                ('surname', models.CharField(max_length=40)),
                ('email', models.CharField(max_length=100)),
                ('phone', models.CharField(max_length=20)),
                ('description', models.CharField(max_length=255)),
                ('date_of_entry', models.DateTimeField(blank=True, null=True)),
                ('creator', models.CharField(blank=True, max_length=20, null=True)),
                ('is_active', models.BooleanField(blank=True, null=True)),
                ('date_of_change', models.DateTimeField(blank=True, null=True)),
                ('modifier', models.CharField(blank=True, max_length=20, null=True)),
                ('type_of_change', models.CharField(max_length=50)),
                ('date_of_archiv', models.DateTimeField(auto_now=True, null=True)),
                ('id_contact', models.IntegerField()),
                ('archiver', models.CharField(blank=True, max_length=20, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='AreaContact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('surname', models.CharField(max_length=40)),
                ('email', models.CharField(max_length=100)),
                ('phone', models.CharField(max_length=20)),
                ('description', models.CharField(max_length=255)),
                ('date_of_entry', models.DateTimeField(auto_now=True, null=True)),
                ('creator', models.CharField(blank=True, max_length=20, null=True)),
                ('is_active', models.BooleanField(blank=True, null=True)),
                ('date_of_change', models.DateTimeField(blank=True, null=True)),
                ('modifier', models.CharField(blank=True, max_length=20, null=True)),
                ('type_of_change', models.CharField(max_length=50)),
                ('id_shops', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='base.areas')),
            ],
        ),
    ]
