# Generated by Django 4.1.2 on 2023-01-09 16:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0029_areacontactarc_areacontact'),
    ]

    operations = [
        migrations.RenameField(
            model_name='areacontact',
            old_name='id_shops',
            new_name='id_area',
        ),
        migrations.RenameField(
            model_name='areacontactarc',
            old_name='id_shops',
            new_name='id_area',
        ),
    ]
