# Generated by Django 4.1.2 on 2023-01-12 17:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0032_alter_areacontact_date_of_change'),
    ]

    operations = [
        migrations.CreateModel(
            name='AreasSpotARC',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_area', models.IntegerField()),
                ('id_spot', models.IntegerField()),
                ('name', models.CharField(max_length=50)),
                ('city', models.CharField(max_length=40)),
                ('street', models.CharField(max_length=50)),
                ('no_building', models.CharField(max_length=30)),
                ('post_code', models.CharField(max_length=20)),
                ('post', models.CharField(max_length=30)),
                ('latitude', models.CharField(max_length=25)),
                ('longitude', models.CharField(max_length=25)),
                ('date_of_entry', models.DateTimeField(blank=True, null=True)),
                ('date_of_change', models.DateTimeField(blank=True, null=True)),
                ('modifier', models.CharField(blank=True, max_length=20, null=True)),
                ('creator', models.CharField(blank=True, max_length=20, null=True)),
                ('is_active', models.BooleanField(blank=True, null=True)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='')),
                ('delivery', models.BooleanField(blank=True, null=True)),
                ('range', models.IntegerField(default=0)),
                ('type_of_change', models.CharField(max_length=50)),
                ('date_of_archiv', models.DateTimeField(auto_now=True, null=True)),
                ('archiver', models.CharField(blank=True, max_length=20, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='AreasSpot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('street', models.CharField(max_length=50)),
                ('no_building', models.CharField(max_length=30)),
                ('post_code', models.CharField(max_length=20)),
                ('post', models.CharField(max_length=30)),
                ('latitude', models.CharField(max_length=25)),
                ('longitude', models.CharField(max_length=25)),
                ('date_of_entry', models.DateTimeField(auto_now=True, null=True)),
                ('date_of_change', models.DateTimeField(blank=True, null=True)),
                ('modifier', models.CharField(blank=True, max_length=20, null=True)),
                ('creator', models.CharField(blank=True, max_length=20, null=True)),
                ('is_active', models.BooleanField(blank=True, null=True)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='')),
                ('delivery', models.BooleanField(blank=True, null=True)),
                ('range', models.IntegerField(default=0)),
                ('type_of_change', models.CharField(max_length=50)),
                ('city', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='base.citis')),
                ('id_area', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='base.areas')),
            ],
        ),
    ]
