# Generated by Django 4.0.5 on 2023-01-12 19:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0033_areasspotarc_areasspot'),
    ]

    operations = [
        migrations.CreateModel(
            name='CitiesDescriptions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(blank=True, max_length=255, null=True)),
                ('language', models.CharField(blank=True, max_length=2, null=True)),
                ('date_of_entry', models.DateTimeField(auto_now_add=True, null=True)),
                ('date_of_change', models.DateTimeField(auto_now=True, null=True)),
                ('creator', models.CharField(blank=True, max_length=5, null=True)),
                ('modifier', models.CharField(blank=True, max_length=5, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ProductGenera',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=50, null=True, unique=True)),
                ('language', models.CharField(blank=True, max_length=2, null=True)),
                ('date_of_entry', models.DateTimeField(auto_now=True, null=True)),
                ('date_of_change', models.DateTimeField(auto_now=True, null=True)),
                ('is_active', models.BooleanField(blank=True, null=True)),
                ('creator', models.CharField(blank=True, max_length=5, null=True)),
                ('modifier', models.CharField(blank=True, max_length=5, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ProductGeneraDescriptions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(blank=True, max_length=255, null=True)),
                ('language', models.CharField(blank=True, max_length=2, null=True)),
                ('date_of_entry', models.DateTimeField(auto_now_add=True, null=True)),
                ('date_of_change', models.DateTimeField(auto_now=True, null=True)),
                ('creator', models.CharField(blank=True, max_length=5, null=True)),
                ('modifier', models.CharField(blank=True, max_length=5, null=True)),
                ('id_product_genera', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='base.productgenera')),
            ],
        ),
        migrations.CreateModel(
            name='ProductSpecies',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=50, null=True, unique=True)),
                ('language', models.CharField(blank=True, max_length=2, null=True)),
                ('date_of_entry', models.DateTimeField(auto_now=True, null=True)),
                ('date_of_change', models.DateTimeField(auto_now=True, null=True)),
                ('is_active', models.BooleanField(blank=True, null=True)),
                ('creator', models.CharField(blank=True, max_length=5, null=True)),
                ('modifier', models.CharField(blank=True, max_length=5, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ProductSpeciesDescriptions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(blank=True, max_length=255, null=True)),
                ('language', models.CharField(blank=True, max_length=2, null=True)),
                ('date_of_entry', models.DateTimeField(auto_now_add=True, null=True)),
                ('date_of_change', models.DateTimeField(auto_now=True, null=True)),
                ('creator', models.CharField(blank=True, max_length=5, null=True)),
                ('modifier', models.CharField(blank=True, max_length=5, null=True)),
                ('id_product_species', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='base.productspecies')),
            ],
        ),
        migrations.CreateModel(
            name='ProductTypes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=50, null=True, unique=True)),
                ('language', models.CharField(blank=True, max_length=2, null=True)),
                ('date_of_entry', models.DateTimeField(auto_now=True, null=True)),
                ('date_of_change', models.DateTimeField(auto_now=True, null=True)),
                ('is_active', models.BooleanField(blank=True, null=True)),
                ('creator', models.CharField(blank=True, max_length=5, null=True)),
                ('modifier', models.CharField(blank=True, max_length=5, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ProductTypesDescriptions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(blank=True, max_length=255, null=True)),
                ('language', models.CharField(blank=True, max_length=2, null=True)),
                ('date_of_entry', models.DateTimeField(auto_now_add=True, null=True)),
                ('date_of_change', models.DateTimeField(auto_now=True, null=True)),
                ('creator', models.CharField(blank=True, max_length=5, null=True)),
                ('modifier', models.CharField(blank=True, max_length=5, null=True)),
                ('id_product_type', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='base.producttypes')),
            ],
        ),
        migrations.CreateModel(
            name='ShopsDescriptions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(blank=True, max_length=255, null=True)),
                ('language', models.CharField(blank=True, max_length=2, null=True)),
                ('date_of_entry', models.DateTimeField(auto_now_add=True, null=True)),
                ('date_of_change', models.DateTimeField(auto_now=True, null=True)),
                ('creator', models.CharField(blank=True, max_length=5, null=True)),
                ('modifier', models.CharField(blank=True, max_length=5, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ShopsSpotDescriptions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(blank=True, max_length=255, null=True)),
                ('language', models.CharField(blank=True, max_length=2, null=True)),
                ('date_of_entry', models.DateTimeField(auto_now_add=True, null=True)),
                ('date_of_change', models.DateTimeField(auto_now=True, null=True)),
                ('creator', models.CharField(blank=True, max_length=5, null=True)),
                ('modifier', models.CharField(blank=True, max_length=5, null=True)),
            ],
        ),
        migrations.DeleteModel(
            name='ProductType',
        ),
        migrations.RemoveField(
            model_name='descriptions',
            name='obj_id',
        ),
        migrations.RemoveField(
            model_name='descriptions',
            name='obj_type',
        ),
        migrations.AddField(
            model_name='descriptions',
            name='id_district',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='base.districts'),
        ),
        migrations.AlterField(
            model_name='citis',
            name='creator',
            field=models.CharField(blank=True, max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='citis',
            name='date_of_change',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AlterField(
            model_name='citis',
            name='date_of_entry',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='citis',
            name='modifier',
            field=models.CharField(blank=True, max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='descriptions',
            name='date_of_change',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AlterField(
            model_name='descriptions',
            name='date_of_entry',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='districts',
            name='creator',
            field=models.CharField(blank=True, max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='districts',
            name='date_of_change',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AlterField(
            model_name='districts',
            name='date_of_entry',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='districts',
            name='modifier',
            field=models.CharField(blank=True, max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='districts',
            name='name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='shops',
            name='creator',
            field=models.CharField(blank=True, max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='shops',
            name='date_of_change',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AlterField(
            model_name='shops',
            name='date_of_entry',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='shops',
            name='modifier',
            field=models.CharField(blank=True, max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='shops',
            name='nip',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='shops',
            name='no_building',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='shops',
            name='post',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='shops',
            name='post_code',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='shops',
            name='street',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='shopsarc',
            name='archiver',
            field=models.CharField(blank=True, max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='shopsarc',
            name='creator',
            field=models.CharField(blank=True, max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='shopsarc',
            name='date_of_archiv',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='shopsarc',
            name='modifier',
            field=models.CharField(blank=True, max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='shopsarc',
            name='nip',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='shopsarc',
            name='no_building',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='shopsarc',
            name='post',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='shopsarc',
            name='post_code',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='shopsarc',
            name='street',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='shopscontact',
            name='creator',
            field=models.CharField(blank=True, max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='shopscontact',
            name='date_of_change',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AlterField(
            model_name='shopscontact',
            name='date_of_entry',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='shopscontact',
            name='modifier',
            field=models.CharField(blank=True, max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='shopscontactarc',
            name='creator',
            field=models.CharField(blank=True, max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='shopscontactarc',
            name='date_of_archiv',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='shopscontactarc',
            name='modifier',
            field=models.CharField(blank=True, max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='shopsspot',
            name='creator',
            field=models.CharField(blank=True, max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='shopsspot',
            name='date_of_change',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AlterField(
            model_name='shopsspot',
            name='date_of_entry',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='shopsspot',
            name='modifier',
            field=models.CharField(blank=True, max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='shopsspotarc',
            name='archiver',
            field=models.CharField(blank=True, max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='shopsspotarc',
            name='city',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='shopsspotarc',
            name='creator',
            field=models.CharField(blank=True, max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='shopsspotarc',
            name='date_of_archiv',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='shopsspotarc',
            name='modifier',
            field=models.CharField(blank=True, max_length=5, null=True),
        ),
        migrations.DeleteModel(
            name='ShopsDescription',
        ),
        migrations.AddField(
            model_name='shopsspotdescriptions',
            name='id_shops_spot',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='base.shops'),
        ),
        migrations.AddField(
            model_name='shopsdescriptions',
            name='id_shops',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='base.shops'),
        ),
        migrations.AddField(
            model_name='productspecies',
            name='id_product_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='base.producttypes'),
        ),
        migrations.AddField(
            model_name='productgenera',
            name='id_product_species',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='base.productspecies'),
        ),
        migrations.AddField(
            model_name='citiesdescriptions',
            name='id_city',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='base.citis'),
        ),
    ]
