# Generated by Django 4.0.5 on 2023-01-13 05:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0034_citiesdescriptions_productgenera_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='productgenera',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='productspecies',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='producttypes',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
