# Generated by Django 4.1.2 on 2023-02-14 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0036_producttypes_uniqueid'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ProductSpecies',
            new_name='ProductSubTypes',
        ),
        migrations.AddField(
            model_name='citis',
            name='language',
            field=models.CharField(blank=True, max_length=2, null=True),
        ),
    ]
