# Generated by Django 4.0.5 on 2023-02-08 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0036_producttypes_uniqueid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productgeneradescriptions',
            name='id_product_genera',
        ),
        migrations.RemoveField(
            model_name='productspecies',
            name='language',
        ),
        migrations.AddField(
            model_name='citis',
            name='country',
            field=models.CharField(blank=True, max_length=2, null=True),
        ),
        migrations.AddField(
            model_name='shopsspot',
            name='kind',
            field=models.CharField(blank=True, max_length=2, null=True),
        ),
        migrations.DeleteModel(
            name='ProductGenera',
        ),
        migrations.DeleteModel(
            name='ProductGeneraDescriptions',
        ),
    ]
