# Generated by Django 4.1.2 on 2023-02-14 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0037_rename_productspecies_productsubtypes_citis_language'),
    ]

    operations = [
        migrations.AddField(
            model_name='productsubtypes',
            name='test',
            field=models.CharField(blank=True, max_length=5, null=True),
        ),
    ]
