# Generated by Django 4.0.5 on 2023-02-08 10:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0037_remove_productgeneradescriptions_id_product_genera_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=50, null=True, unique=True)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='')),
                ('date_of_entry', models.DateTimeField(auto_now=True, null=True)),
                ('date_of_change', models.DateTimeField(auto_now=True, null=True)),
                ('is_active', models.BooleanField(blank=True, null=True)),
                ('creator', models.CharField(blank=True, max_length=5, null=True)),
                ('modifier', models.CharField(blank=True, max_length=5, null=True)),
                ('id_product_species', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='base.productspecies')),
            ],
        ),
        migrations.CreateModel(
            name='ProductDescriptions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(blank=True, max_length=255, null=True)),
                ('language', models.CharField(blank=True, max_length=2, null=True)),
                ('date_of_entry', models.DateTimeField(auto_now_add=True, null=True)),
                ('date_of_change', models.DateTimeField(auto_now=True, null=True)),
                ('creator', models.CharField(blank=True, max_length=5, null=True)),
                ('modifier', models.CharField(blank=True, max_length=5, null=True)),
                ('id_product', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='base.product')),
            ],
        ),
    ]
