# Generated by Django 4.1.2 on 2023-02-14 19:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0038_productsubtypes_test'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productsubtypes',
            name='test',
        ),
    ]
