# Generated by Django 4.1.2 on 2023-02-14 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0039_remove_productsubtypes_test'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productsubtypes',
            name='language',
        ),
        migrations.AddField(
            model_name='productsubtypes',
            name='languageTest',
            field=models.CharField(blank=True, max_length=2, null=True),
        ),
    ]
