# Generated by Django 4.0.5 on 2023-02-09 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0039_shopsspotarc_kind_alter_shopsspot_kind'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shopsspot',
            name='city',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='shopsspot',
            name='kind',
            field=models.CharField(blank=True, max_length=5, null=True),
        ),
    ]
