# Generated by Django 4.1.2 on 2023-02-14 19:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0040_remove_productsubtypes_language_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='productsubtypes',
            old_name='languageTest',
            new_name='language',
        ),
    ]
