# Generated by Django 4.1.2 on 2023-02-15 16:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0041_rename_languagetest_productsubtypes_language'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductSubTypesTest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=50, null=True, unique=True)),
                ('language', models.CharField(blank=True, max_length=2, null=True)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='')),
                ('date_of_entry', models.DateTimeField(auto_now=True, null=True)),
                ('date_of_change', models.DateTimeField(auto_now=True, null=True)),
                ('is_active', models.BooleanField(blank=True, null=True)),
                ('creator', models.CharField(blank=True, max_length=5, null=True)),
                ('modifier', models.CharField(blank=True, max_length=5, null=True)),
                ('id_product_type', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='base.producttypes')),
            ],
        ),
        migrations.AlterField(
            model_name='productgenera',
            name='id_product_species',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='base.productsubtypestest'),
        ),
        migrations.AlterField(
            model_name='productspeciesdescriptions',
            name='id_product_species',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='base.productsubtypestest'),
        ),
        migrations.DeleteModel(
            name='ProductSubTypes',
        ),
    ]
