# Generated by Django 4.1.2 on 2023-02-15 16:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0043_productsubtypes_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productsubtypes',
            name='language',
        ),
    ]
