# Generated by Django 4.1.2 on 2023-02-16 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0045_remove_productgenera_language_and_more'),
    ]

    operations = [
        # migrations.AddField(
        #     model_name='productgenera',
        #     name='language',
        #     field=models.CharField(blank=True, max_length=2, null=True),
        # ),
        # migrations.AddField(
        #     model_name='productgeneradescriptions',
        #     name='language',
        #     field=models.CharField(blank=True, max_length=2, null=True),
        # ),
        migrations.AddField(
            model_name='productspeciesdescriptions',
            name='language',
            field=models.CharField(blank=True, max_length=2, null=True),
        ),
        migrations.AddField(
            model_name='productsubtypes',
            name='language',
            field=models.CharField(blank=True, max_length=2, null=True),
        ),
        migrations.AddField(
            model_name='producttypesdescriptions',
            name='language',
            field=models.CharField(blank=True, max_length=2, null=True),
        ),
    ]
