# Generated by Django 4.1.2 on 2023-02-16 18:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0046_productgenera_language_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productsubtypes',
            name='language',
        ),
    ]
