# Generated by Django 4.1.2 on 2023-02-21 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0047_remove_productsubtypes_language'),
    ]

    operations = [
        migrations.AddField(
            model_name='productsubtypes',
            name='uniqueId',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
