# Generated by Django 4.1.2 on 2023-02-22 17:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0048_productsubtypes_uniqueid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shopsspotdescriptions',
            name='id_shops_spot',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='base.shopsspot'),
        ),
    ]
