# Generated by Django 4.0.5 on 2023-03-01 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0049_alter_shopsspotdescriptions_id_shops_spot'),
    ]

    operations = [
        migrations.AddField(
            model_name='shopsspot',
            name='kind',
            field=models.CharField(blank=True, max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='shopsspot',
            name='city',
            field=models.CharField(max_length=50),
        ),
    ]
