# Generated by Django 4.0.5 on 2023-03-01 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0050_shopsspot_kind_alter_shopsspot_city'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ProductSpeciesDescriptions',
            new_name='ProductSubTypesDescriptions',
        ),
        migrations.RemoveField(
            model_name='productgenera',
            name='id_product_species',
        ),
        migrations.RemoveField(
            model_name='productgeneradescriptions',
            name='id_product_genera',
        ),
        migrations.AlterField(
            model_name='areasspot',
            name='city',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='areasspot',
            name='date_of_entry',
            field=models.DateTimeField(auto_now=True, default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='areasspotarc',
            name='city',
            field=models.CharField(max_length=50),
        ),
        migrations.DeleteModel(
            name='Place_of_pickups',
        ),
        migrations.DeleteModel(
            name='ProductGenera',
        ),
        migrations.DeleteModel(
            name='ProductGeneraDescriptions',
        ),
    ]
